// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"follow/follow"
	"follow/internal/logic"
	"follow/internal/svc"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) PostFollow(ctx context.Context, in *follow.PostFollowRequest) (*follow.Response, error) {
	l := logic.NewPostFollowLogic(ctx, s.svcCtx)
	return l.PostFollow(in)
}

func (s *FollowServer) GetFans(ctx context.Context, in *follow.GetFansRequest) (*follow.GetFansResponse, error) {
	l := logic.NewGetFansLogic(ctx, s.svcCtx)
	return l.GetFans(in)
}

func (s *FollowServer) GetFollowingList(ctx context.Context, in *follow.GetFollowingListRequest) (*follow.GetFollowingListResponse, error) {
	l := logic.NewGetFollowingListLogic(ctx, s.svcCtx)
	return l.GetFollowingList(in)
}
