#mysql config
MysqlConfig :
  Name         : root
  Password     : sx221410
  Ip           : localhost
  Port         : 701
  DatabaseName : tiktok

#redis config
RedisConfig :
  Network  : tcp
  Address  : localhost:6379
  Num      : 0
  RdbPassword :

#JWT secret key
JwtKey : tyhngebvfpliyergfgdf

#QiniuOss
OSSConfig :
  AccessKey     :
  SecretKey     :
  VideoBucket   :
  PictureBucket :
  DomainVideo   :
  DomainPicture :

# 单次feed流所能刷取的最大视频量
N : 10
