#mysql config
MysqlConfig :
  Name         : root
  Password     : sx221410
  Ip           : 43.143.134.182
  Port         : 701
  DatabaseName : tiktok

#redis config
RedisConfig :
  Network  : tcp
  Address  : 43.143.134.182:6379
  Num      : 0
  RdbPassword :

#JWT secret key
JwtKey : tyhngebvfpliyergfgdf

#QiniuOss
OSSConfig :
  AccessKey     : XuigBGSCJ7vpAtRtpu04NqLGLXpEROCaqgOxTZ0W
  SecretKey     : mhV_z93CyJCcDTmSfU2cSfx_LiejWCjujCCRMuqg
  VideoBucket   : http://s1h4imhnw.bkt.clouddn.com
  PictureBucket : http://s1h4sripn.bkt.clouddn.com
  DomainVideo   : storage.ZoneHuadongZheJiang2
  DomainPicture : storage.ZoneHuadongZheJiang2

# 单次feed流所能刷取的最大视频量
N : 10
