// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserLoginResponse struct {
	StatusCode int    `json:"status_code"`
	UserId     int    `json:"user_id"`
	Token      string `json:"token"`
	StatusMsg  string `json:"status_msg"`
}

type UserRegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserRegisterResponse struct {
	StatusCode int    `json:"status_code"`
	UserId     int    `json:"user_id"`
	Token      string `json:"token"`
	StatusMsg  string `json:"status_msg"`
}
