// Code generated by goctl. DO NOT EDIT.
package types

type VideoListRequest struct {
	UserId uint `json:"userId,optional"`
}

type VideoListResponse struct {
	StatusCode int            `json:"status_code"`
	VideoList  []VideoListRes `json:"video_list"`
}

type VideoListRes struct {
	ID       int       `json:"id"`
	Author   AuthorRes `json:"author"`
	PlayURL  string    `json:"play_url"`
	CoverURL string    `json:"cover_url"`
}

type AuthorRes struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserInfoRequest struct {
	Token string `form:"token"`
}

type UserInfoResponse struct {
	StatusCode int      `json:"status_code"`
	StatusMsg  string   `json:"status_msg"`
	User       UserInfo `json:"user"`
}

type UserInfo struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserLoginResponse struct {
	StatusCode int    `json:"status_code"`
	UserId     int    `json:"user_id"`
	Token      string `json:"token"`
	StatusMsg  string `json:"status_msg"`
}

type UserRegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserRegisterResponse struct {
	StatusCode int    `json:"status_code"`
	UserId     int    `json:"user_id"`
	Token      string `json:"token"`
	StatusMsg  string `json:"status_msg"`
}

type PublishRequest struct {
	Token   string `form:"token"`
	Title   string `form:"title"`
	PlayURL string `form:"playUrl,optional"`
}

type PublishResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
