// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package followclient

import (
	"context"

	"mini-tiktok/service/follow/follow"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFansRequest           = follow.GetFansRequest
	GetFansResponse          = follow.GetFansResponse
	GetFollowingListRequest  = follow.GetFollowingListRequest
	GetFollowingListResponse = follow.GetFollowingListResponse
	GetFriendListRequest     = follow.GetFriendListRequest
	GetFriendListResponse    = follow.GetFriendListResponse
	PostFollowRequest        = follow.PostFollowRequest
	Response                 = follow.Response
	User                     = follow.User

	Follow interface {
		PostFollow(ctx context.Context, in *PostFollowRequest, opts ...grpc.CallOption) (*Response, error)
		GetFans(ctx context.Context, in *GetFansRequest, opts ...grpc.CallOption) (*GetFansResponse, error)
		GetFollowingList(ctx context.Context, in *GetFollowingListRequest, opts ...grpc.CallOption) (*GetFollowingListResponse, error)
		GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

func (m *defaultFollow) PostFollow(ctx context.Context, in *PostFollowRequest, opts ...grpc.CallOption) (*Response, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.PostFollow(ctx, in, opts...)
}

func (m *defaultFollow) GetFans(ctx context.Context, in *GetFansRequest, opts ...grpc.CallOption) (*GetFansResponse, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.GetFans(ctx, in, opts...)
}

func (m *defaultFollow) GetFollowingList(ctx context.Context, in *GetFollowingListRequest, opts ...grpc.CallOption) (*GetFollowingListResponse, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.GetFollowingList(ctx, in, opts...)
}

func (m *defaultFollow) GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error) {
	client := follow.NewFollowClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}
